=== guima-seifer/EngWeb/Semana 5/homework/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pr (meta, workteam, abstract, deliverables) >

<!ELEMENT meta (keyname, title, subtitle?, bdate, edate, supervisor) >
<!ELEMENT keyname (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT bdate (#PCDATA) >
<!ELEMENT edate (#PCDATA) >

<!ELEMENT supervisor (name, email?, url?) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT url (#PCDATA) >

<!ELEMENT workteam (member+) >
<!ELEMENT member (name, email, id) >
<!ELEMENT id (#PCDATA) >
<!ATTLIST member id ID #REQUIRED >

<!ELEMENT abstract (p | figure | table | code)+ >
<!ELEMENT p (#PCDATA|b|i|u|iref|xref|ackro | code)* >
<!ELEMENT b (#PCDATA|i|u|iref|xref|ackro)* >
<!ELEMENT i (#PCDATA|b|u|iref|xref|ackro)* >
<!ELEMENT u (#PCDATA|b|i|iref|xref|ackro)* >
<!ELEMENT figure (img, caption) >
<!ELEMENT caption (#PCDATA) >
<!ELEMENT img EMPTY >
<!ATTLIST img
            path CDATA #REQUIRED
            desc CDATA #IMPLIED>
<!ELEMENT code (#PCDATA) >
<!ATTLIST code
            lang CDATA #IMPLIED>
<!ELEMENT table (tr+) >
<!ELEMENT tr (cel+) >
<!ELEMENT cel (#PCDATA) >

<!ELEMENT ackro (short, extended?) >
<!ELEMENT short (#PCDATA) >
<!ELEMENT extended (#PCDATA) >

<!ELEMENT iref (#PCDATA) >
<!ATTLIST iref
    url CDATA #REQUIRED >
    
<!ELEMENT xref (#PCDATA) >
<!ATTLIST xref
    url CDATA #REQUIRED >
    
<!ELEMENT deliverables (deliverable+) >
<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable url CDATA #IMPLIED >

=== guima-seifer/EngWeb/Semana 3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE pr SYSTEM "PR.dtd">

<pr>
    <meta>
        <keyname>TP3</keyname>
        <title>Trabalho Prático Semana 3</title>
        <bdate>Setembro de 2017</bdate>
        <edate>Setembro de 2017</edate>
        <supervisor>
            <name>José Carlos Ramalho</name>    
        </supervisor>
    </meta>
    
    <workteam>
        <member id="a1">
            <name>Fernando Guimarães</name>
            <email>fernando.b.v.guimaraes@gmail.com</email>
            <id>70012</id>
        </member>
    </workteam>


    <abstract>
        <p>
Projeção de um documento <ackro><short>html</short></ackro> para o formato <ackro><short>DRD</short></ackro>. 
            Para realização deste exercício, foi necessário uma declaração de conteúdo misto 
            para declarar a estrutura de texto com as suas diferentes ênfases, <i>itálico</i>,
            <b>negrito</b> e <ackro><short>ACKRO</short></ackro>.
        </p>
        <p> Para poder efetuar a conversão do ficheiro <i>arq</i>.<ackro><short>XML</short></ackro> para o formato .<ackro><short>DTD</short></ackro> é utilizada uma ferramenta do <b>Oxygen</b>.
            Tools -> Generate/Convert Schema, seleciona-se o ficheiro <ackro><short>XML</short></ackro> em questão como <i>input</i> e define-se o nome do <i>output</i> <ackro><short>DTD</short></ackro> resultante.
        </p>
    </abstract>
 
       <deliverables>
           <deliverable url="PR.dtd">Project Record .DTD file</deliverable>
           <deliverable url="PR.xml">Project Record .XML file</deliverable>           
       </deliverables>
</pr>

=== guima-seifer/EngWeb/Semana 4/tp4.xml
<?xml version="1.0" encoding="UTF-8"?>
 

<!DOCTYPE pr SYSTEM "PR.dtd">

<pr>
    <meta>
        <keyname>EngWeb::A70012::TP4</keyname>
        <title>Trabalho Prático Semana 4</title>
        <bdate>Setembro de 2017</bdate>
        <edate>Setembro de 2017</edate>
        <supervisor>
            <name>José Carlos Ramalho</name>    
        </supervisor>
    </meta>
    
    <workteam>
        <member id="a1">
            <name>Fernando Guimarães</name>
            <email>fernando.b.v.guimaraes@gmail.com</email>
            <id>70012</id>
        </member>
    </workteam>


    <abstract>
        <p>
            Geração de páginas <ackro><short>Html</short> <extended>HyperText Markup Language</extended></ackro> para projeção dos documentos: <i>Project Record</i>, Trabalho Prático Semana 4 e para o Arquivo de Músicas Tradicionais
            a partir de dados <ackro><short>XML</short><extended>Extensible Markup Language</extended></ackro> através da liguagem de transformação <ackro><short>XSL</short><extended>Extensible Stylesheet Language</extended></ackro>.
            Criação e população de listas, com referências <ackro><short>html</short></ackro>, <i>queries</i> <b>XPath</b> para ordenação e organização destas mesmas listas.
            
        </p>
        <p></p>
    </abstract>
 
       <deliverables>
           <deliverable url="./arq-son-EVO.xml"> Arquivo de Música tradicionais (XML)</deliverable>  
           <deliverable url="./arq-son-EVO.xsl">Arquivo de Música tradicionais (XSL)</deliverable>           
           <deliverable url="./musicas.html">Arquivo de Música tradicionais (HTML)</deliverable>           
           <deliverable url="./tp4.xml">Project Record 4 (XML)</deliverable>      
           <deliverable url="./tp4.html">Project Record 4 (HTML)</deliverable>
       </deliverables>
</pr>

=== guima-seifer/EngWeb/Semana 5/homework/tp5.xml
<?xml version="1.0" encoding="UTF-8"?>
 

<!DOCTYPE pr SYSTEM "PR.dtd">

<pr>
    <meta>
        <keyname>EngWeb::A70012::TP5</keyname>
        <title>Trabalho Prático Semana 5</title>
        <bdate>Outubro de 2017</bdate>
        <edate>Outubro de 2017</edate>
        <supervisor>
            <name>José Carlos Ramalho</name>    
        </supervisor>
    </meta>
    
    <workteam>
        <member id="a1">
            <name>Fernando Guimarães</name>
            <email>fernando.b.v.guimaraes@gmail.com</email>
            <id>70012</id>
        </member>
    </workteam>


    <abstract>
        <p>
            Para gerar páginas de forma numerada é necessário ter em consideração que as variáveis no ambiente  <ackro><short>XSL</short><extended>Extensible Stylesheet Language</extended></ackro> são imutáveis. Para conseguir associar uma página <ackro><short>Html</short> <extended>HyperText Markup Language</extended></ackro> a uma entrada <code>//doc</code> associa-se a variável à <b>position()</b> do nó na árvore xml. 
        Esta associação está embrulhada num elemento <code>xml: for-each</code> que permite aplicar o mesmo template a todos os nós selecionados, existindo uma variável "nova" a cada iteração do ciclo com o valor correspondente à posição na árvore.
        </p>
            
        <p>Para executar o servidor <b>nodejs</b>:
            Abrir o terminal na diretoria <code>homework</code> e executar o comando <code>node servidor.js&amp;</code>;
            Posteriormente, assim que o <i>daemon</i> estiver a correr, deve-se indicar o seguinte endereço no browser, <b>localhost:7777/<i>XXX</i></b>  em que <b><i>XXX</i></b> corresponde a um valor entre <b>1 e 448</b> - este intervalo é o número de páginas  <ackro><short>Html</short></ackro> geradas para o website do exercício; 
            </p>
        
       <p>Esta solução não permite a utilização das funcionalidades "Anterior" e "Seguinte" ou até mesmo o "Índice".</p>
    </abstract>
 
       <deliverables>
           <deliverable url="./arq-son-EVO.xml"> Arquivo de Música tradicionais (XML)</deliverable>  
           <deliverable url="./arq-son-EVO.xsl">Arquivo de Música tradicionais (XSL)</deliverable>           
           <deliverable url="./tp5.xml">Document Type Definition do Project Record 5 (DTD)</deliverable>
           <deliverable url="./tp5.xml">Project Record 5 (XML)</deliverable>      
           <deliverable url="./tp5.html">Project Record 5 (HTML)</deliverable>
           <deliverable url="./website">Pasta com Arquivos Sonoros</deliverable>
           <deliverable url="./server.js">Servidor NodeJS (JS)</deliverable>
       </deliverables>
</pr>
